### ISSUE TITLE
please provide the dataset used for this project

### ISSUE THREAD

**Issue by millermuttu** [firmamentone/masksDetection#1]
@firmamentone 
hi thanks for the project.
it will be grate help if you share the dataset google drive link.

thanks in advance.

**Comment by firmamentone** [comment]
Hi millermittu,

Sorry about my late reply
This is the zip file that includes the images and labels.
The folder structure is for the ImageAI "custom object detection training". You can use it to test the machine learning.
https://drive.google.com/file/d/1zfHTPsRipj-T_wWEjFHEijC0wx4Z6qVd/view?usp=sharing

If the link is unaccessible, please tell me. thanks!

**Comment by millermuttu** [comment]
the link works, thankyou so much for the data, 

Cudos to your work...
